const KOFI_URL = 'https://ko-fi.com/khalidkhoury';
const QUICK_OFFSETS = { '1h': 60, 'tomorrow9': 'tomorrow9', '1w': 10080 };
function pad(n){return String(n).padStart(2,'0')}
function toLocalInputDate(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function formatDateTime(ms){return new Date(ms).toLocaleString([], {dateStyle:'medium', timeStyle:'short'})}
function convertTo24Hour(hour, minute, ampm){let h=Number(hour); const m=Number(minute); if(!Number.isInteger(h)||h<1||h>12||!Number.isInteger(m)||m<0||m>59) throw new Error('Choose a valid time.'); if(ampm==='AM'&&h===12)h=0; if(ampm==='PM'&&h!==12)h+=12; return {hour:h, minute:m}}
function getReminderMs(form){const date=form.querySelector('[name="date"]').value; const hour=form.querySelector('[name="hour"]').value; const minute=form.querySelector('[name="minute"]').value; const ampm=form.querySelector('[name="ampm"]').value; if(!date) throw new Error('Choose a reminder date.'); const t=convertTo24Hour(hour, minute, ampm); const [y,mo,d]=date.split('-').map(Number); const when=new Date(y,mo-1,d,t.hour,t.minute,0,0).getTime(); if(when<=Date.now()) throw new Error('Reminder time must be in the future.'); return when}
function applyDate(form, date){form.querySelector('[name="date"]').value=toLocalInputDate(date); let h=date.getHours(); const ampm=h>=12?'PM':'AM'; h=h%12||12; form.querySelector('[name="hour"]').value=String(h); form.querySelector('[name="minute"]').value=pad(date.getMinutes()); form.querySelector('[name="ampm"]').value=ampm}
function setQuick(form, key){const now=new Date(); let d;if(QUICK_OFFSETS[key]==='tomorrow9'){d=new Date(now); d.setDate(d.getDate()+1); d.setHours(9,0,0,0)}else{d=new Date(now.getTime()+QUICK_OFFSETS[key]*60000)} applyDate(form,d)}
function createReminderForm(root, context={}){root.innerHTML=`<div class="card"><h1>ActLater</h1><form><label>Title</label><input name="title" required><label>Note</label><textarea name="note" placeholder="Why do you want to try this later?"></textarea><label>Quick reminder</label><div class="row quick"><button type="button" data-quick="1h" class="secondary">1 hour</button><button type="button" data-quick="tomorrow9" class="secondary">Tomorrow 9 AM</button><button type="button" data-quick="1w" class="secondary">1 week</button></div><label>Date</label><input name="date" type="date" required><div class="grid"><label>Hour<select name="hour"></select></label><label>Minute<select name="minute"></select></label><label>AM / PM<select name="ampm"><option>AM</option><option>PM</option></select></label></div><div class="row"><button type="button" data-test>Test notification</button><button type="submit">Save & remind me</button><button type="button" data-dashboard class="secondary">Dashboard</button><a class="button secondary" href="${KOFI_URL}" target="_blank" rel="noopener">Ko-fi</a></div><div class="status" role="status"></div></form></div>`; const form=root.querySelector('form'); const hour=form.hour; for(let i=1;i<=12;i++) hour.add(new Option(String(i),String(i))); for(let i=0;i<60;i++) form.minute.add(new Option(pad(i),pad(i))); const in30=new Date(Date.now()+30*60000); applyDate(form,in30); form.title.value=context.title||''; form.note.value=context.note||''; const status=form.querySelector('.status'); form.querySelectorAll('[data-quick]').forEach(b=>b.addEventListener('click',()=>setQuick(form,b.dataset.quick))); form.querySelector('[data-dashboard]').addEventListener('click',()=>chrome.runtime.sendMessage({type:'OPEN_DASHBOARD'})); form.querySelector('[data-test]').addEventListener('click',()=>chrome.runtime.sendMessage({type:'TEST_NOTIFICATION'},r=>{status.textContent=r?.ok?'Test notification sent.':(r?.error||'Unable to send notification.')})); form.addEventListener('submit',e=>{e.preventDefault(); try{const reminderAt=getReminderMs(form); const item={id:crypto.randomUUID(),title:form.title.value.trim(),note:form.note.value.trim(),url:context.url||'',sourceTitle:context.sourceTitle||'',createdAt:Date.now(),reminderAt,tried:false}; if(!item.title) throw new Error('Add a title.'); chrome.runtime.sendMessage({type:'SAVE_REMINDER',item},r=>{status.textContent=r?.ok?`Saved for ${formatDateTime(reminderAt)}.`:(r?.error||'Save failed.');});}catch(err){status.textContent=err.message}}); return form}
